## uml: Use cases 


```plantuml
@startuml
left to right direction
:User: << Human >>
:InfluxDB: << DataSource >>
:Server: <<Computer to monitor>>


(Select server)
User --> (Select server)

(Add server)
User --> (Add Server)


(See stats)
User ---> (See stats)
(See stats) <--- InfluxDB : Sending host data

(Adding stats)
Server ---> (Adding stats) : Sending infos like CPU and RAM usage
(Adding stats) ---> InfluxDB : Adding it to the time series database

@enduml

```